---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: docs/index.md
  label: introduction
- type: directory
  path: docs/hosting
  label: hosting
  create: all
  match: "**/*"
- type: directory
  path: docs/internet-computer-hosting
  label: internet computer hosting
  create: all
  match: "**/*"
- type: directory
  path: docs/storage
  label: storage
  create: all
  match: "**/*"
- type: directory
  path: docs/fleek-cli
  label: fleek cli
  create: all
  match: "**/*"
- type: directory
  path: docs/filecoin-archiving
  label: filecoin archiving
  create: all
  match: "**/*"
- type: directory
  path: docs/space-daemon
  label: space daemon
  create: all
  match: "**/*"
- type: directory
  path: docs/space-sdk
  label: space sdk
  create: all
  match: "**/*"
- type: directory
  path: docs/tutorials
  label: tutorials
  create: all
  match: "**/*"
- type: directory
  path: docs/examples
  label: examples
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
